name: CEShop
main: Aericio\PCEBookShop\PCEBookShop
version: 1.0.0
api: 3.0.0
load: POSTWORLD
author: Aericio
depend: [PiggyCustomEnchants]
website: "https://github.com/Aericio/PCEBookShop/"
permissions:
  ceshop:
    default: op
    description: "Allows usage of all PCEBookShop features"
    children:
      ceshop.command:
        default: op
        description: "Allows usage of all PCEBookShop commands"
        children:
          ceshop.command.shop:
            default: true
            description: "Allows usage of the /ceshop command"
